export const USER_STATUS = {
  VERIFICATION: 'VERIFICATION',
  ACTIVE: 'ACTIVE'
}

export const VERIFICATION_METHOD = {
  PHONE: 'PHONE',
  EMAIL: 'EMAIL'
}

export const ASSET_TYPE = {
  DRAMA_VIDEO: 'DRAMA_VIDEO',
  USER_AVATAR: 'USER_AVATAR',
  CHALLENGE_VIDEO: 'CHALLANGE_VIDEO',
  CHANNEL_VIDEO: 'CHANNEL_VIDEO'
}

export const CHALLENGE_STATUS = {
  ACTIVE: 'ACTIVE',
  PAST: 'PAST',
  REVIEW: 'REVIEW',
  NOT_CONSIDERING: 'NOT_CONSIDERING',
  DECLINED: 'DECLINED',
  DRAFT: 'DRAFT',
  HIDDEN: 'HIDDEN'
}

export const PRIZE_STATUS = {
  COLLECTED: 'COLLECTED',
  WON: 'WON'
}

export const NOTIFICATION_TYPES = {
  NEW_RESPONSE: 'NEW_RESPONSE',
  NEW_CHALLENGE: 'NEW_CHALLANGE',
  NEW_WIN: 'NEW_WIN',
  CH_ACK: 'CH_ACK',
  CH_DECLINED: 'CH_DECLINED',
  CH_NOT_CONSIDERING: 'CH_NOT_CONSIDERING',
  NEW_CHANNEL: 'NEW_CHANNEL',
  CMS_ADMIN_NEW_CHALLENGE: 'CMS_ADMIN_NEW_CHALLENGE',
  CMS_ADMIN_NEW_CHANNEL: 'CMS_ADMIN_NEW_CHANNEL',
  CMS_ADMIN_GRANDPRIZE: 'CMS_ADMIN_GRANDPRIZE',
  NEW_VIDEO: 'NEW_VIDEO',
  CMS_GENERAL_NOTIFICATION: 'CMS_GENERAL_NOTIFICATION',
  BIRTHDAY_CHALLENGE: 'BIRTHDAY_CHALLENGE',
  BIRTHDAY_WINNER: 'BIRTHDAY_WINNER'
}

export const REACTION_TYPES = {
  SAD: 'SAD',
  NICE: 'NICE',
  OH: 'OH',
  ANGRY: 'ANGRY'
}

export const REPORT_TYPE = {
  DRAMA: 'Drama',
  USER: 'User'
}

export const REPORT_MESSAGE = {
  OFFENSIVE: 'OFFENSIVE',
  VIOLENT: 'VIOLENT',
  NUDITY: 'NUDITY',
}

export const TUTORIAL_SCREEN = {
  INTRO: 'INTRO',
  HOME_CHALLENGE: 'HOME_CHALLENGE',
  CHALLENGE_SCREEN: 'CHALLENGE_SCREEN'
}

export const RANKING = {
  NOVICE: 'Novice',
  BEGINNER: 'Beginner',
  ADVANCED_BEGINNER: 'Advanced Beginner',
  COMPETENT: 'Competent',
  PROFICIENT: 'Proficient',
  EXPERT: 'Expert',
  PRO: 'Pro',
  ELITE: 'Elite',
  MASTER: 'Master',
  GOD_ESS: 'God/Godess'
}

export const SCREEN = {
  SETTINGS: 'SETTINGS',
  HOME: 'HOME'
}

export const ERROR_TYPE = {
  PHONE_TAKEN: 'PHONE_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN'
}

export const CHALLENGES_SCREEN = {
  VERSUZ: 'VERSUZ',
  YOUR_CHALLENGES: 'YOUR_CHALLENGES'
}